out.exe:closestPairImp.o closestPairApp.o
	        g++ -o out.exe closestPairImp.o closestPairApp.o
closestPairImp.o:closestPairImp.cpp
	        g++ -c closestPairImp.cpp
closestPairApp.o:closestPairApp.cpp
	        g++ -c closestPairApp.cpp
