out.exe:cpuScheduling.o cpuSchedulingApp.o
	cc -o out.exe cpuScheduling.o cpuSchedulingApp.o
cpuScheduling.o:cpuScheduling.c
	cc -c cpuScheduling.c
cpuSchedulingApp.o:cpuSchedulingApp.c
	cc -c cpuSchedulingApp.c
